def xor(data: bytes, key: int) -> bytes: ...
def cyclic_xor(data: bytes, key: bytes) -> bytes: ...
def cyclic_xor_unsafe(data: bytes, key: bytes) -> bytes: ...
def xor_in_place(data: bytearray, key: int) -> None: ...
def cyclic_xor_in_place(data: bytearray, key: bytes) -> None: ...
def cyclic_xor_in_place_unsafe(data: bytearray, key: bytes) -> None: ...
